<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Asian Leaderboard - Community Rankings</title>
    <link rel="stylesheet" href="style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800;900&display=swap" rel="stylesheet">
</head>
<body>
    <header class="top-nav">
        <div class="container">
            <div class="nav-brand">Asian Leaderboard</div>
            <div class="nav-options">
                <div class="nav-item india-tab active" data-tab="india">INDIA</div>
                <div class="nav-item nepal-tab" data-tab="nepal">NEPAL</div>
                <a href="https://dsc.gg/asianlb" target="_blank" class="discord-btn">DISCORD</a>
            </div>
        </div>
    </header>

    <main class="container">
        <!-- India Ranking Section -->
        <section id="india-section" class="ranking-section active">
            <h2 class="section-title">India Rankings</h2>
            <div class="top-list" id="india-list">
                <!-- 10 items will be generated by JS -->
            </div>
        </section>

        <!-- Nepal Ranking Section -->
        <section id="nepal-section" class="ranking-section">
            <h2 class="section-title">Nepal Rankings</h2>
            <div class="top-list" id="nepal-list">
                <!-- 10 items will be generated by JS -->
            </div>
        </section>

        <!-- Discord Style Profile Card -->
        <section id="profile-card" class="profile-overlay">
            <div class="card-content">
                <button class="close-btn">&times;</button>
                <div class="profile-banner"></div>
                <div class="pfp-wrapper">
                    <div class="pfp-container">
                        <img id="discord-pfp" src="https://cdn.discordapp.com/embed/avatars/0.png" alt="Discord PFP">
                    </div>
                </div>
                <div class="profile-body">
                    <div class="rank-badge" id="player-rank">Top 1</div>
                    <h3 class="profile-name" id="player-name">Username</h3>
                    <p class="profile-id-sub" id="player-id-display">ID: ---</p>
                    
                    <div class="profile-roles-section">
                        <p class="roles-title">Roles</p>
                        <div class="roles-container" id="player-roles">
                            <!-- Role tags will be added here -->
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <div class="container">
            <p>&copy; 2024 Asian Leaderboard - Unity of India & Nepal</p>
        </div>
    </footer>

    <script src="script.js?v=25"></script>
</body>
</html>
